apiVersion: ENC[AES256_GCM,data:lR8=,iv:1QTLxz11XvKgdykO/7CpD7s6kiDzgoaLHxsxSXB3OH0=,tag:hTTIQetnWukzS9al9/5vNg==,type:str]
kind: ENC[AES256_GCM,data:qGQFLY/2,iv:EBC9Z+SSjN0fdvpeVZILQuU4l2HF9VRPMfNW9Z3bNK0=,tag:rEnm53HlrG+rqOwSqgbxiA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:aY29p/RGYcHeJ32hhpQUCwXh,iv:F57H86M9LHHOw+A7/WkyZWoij/6UFT6+RQb7ReATTWw=,tag:x+L0Q8mU72dESN8SuYj2Ow==,type:str]
    namespace: ENC[AES256_GCM,data:O2eCHj87nog=,iv:dvmAN1UlvdKmx950rc+ZerkbqfVUs3Ti4psjoNywK1g=,tag:IALO+IppISIpo4mMZsU3Sw==,type:str]
type: ENC[AES256_GCM,data:5V3vr6Ny,iv:b9oT/qRafnKVeDSZQ0n8TBBa2PgLZ1SA00FWH3In2F4=,tag:QnPNRLNhl0BVGkiNxQRQEA==,type:str]
stringData:
    API_SECRET: ENC[AES256_GCM,data:O7FdOgvqXodLhyaQyrM6n+26JIrwvyA=,iv:+NF4coazKAGOug6kokGJUbPRxpihX2O03g8Dnunfac4=,tag:nh1SErElJHhr7RKttJINDA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvWkNIUmQ3MldPU3JUQnBr
            MFE2eXNEczRPUHBXdzl4ZXduUHA4ZDFQcTNBCnZxeDNoWjlOT3J5MHQyTUw5Wktn
            SmpsWkh4QWR4S1AzNmpFcVp4T1JQbGsKLS0tIHBhNjAvWXpLZEdmbnlaOHlNVmtO
            U1Y0TnFtdkl6dTE0OS91TDdxQ2tVMk0KaykM9ETnIirbsWomfMxyCklW08ZaM6A/
            5+Z/3/OJCuoeqriT57HJjOjqqy5KBHCMBS9NV8n/Z3G2U4kiKc7gTQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1fujz6du920s07nddtqymkwzq7xsg2kejttvyl374mhre45ectqhq9tx3xm
    lastmodified: "2026-07-27T20:20:59Z"
    mac: ENC[AES256_GCM,data:VmzYD3VeMy7H/0xPxhQOsG6RcrHLVlpbT/zlEZeTcxLuJ6FdkxGrm20NdBrlVLCvVGkZ4hFc1conBH/0Epm1pc+AkT7GpfdWxyb09HTv8EqTnFQ/c1lWADdwBE0+hyjeDiRSWsnjNfyVXTKiyuSQqf50dV5Hh8MvIdjWH4V1ebQ=,iv:2CHYJhfiNBQoSiRWIqxSF6BnCLnk5pMEZfY8h6I8vv4=,tag:U10HWkisp1dDO66RbOUb5w==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
