apiVersion: v1
kind: ServiceAccount
metadata:
  name: unauthorized-client
  namespace: payments

---

apiVersion: v1
kind: Pod
metadata:
  name: unauthorized-client
  namespace: payments
  labels:
    app: unauthorized-client

spec:

  serviceAccountName: unauthorized-client

  containers:

    - name: curl
      image: curlimages/curl

      command:
        - sleep
        - "3600"

      securityContext:
        allowPrivilegeEscalation: false
        runAsNonRoot: true
        runAsUser: 10001

        capabilities:
          drop:
            - ALL

        seccompProfile:
          type: RuntimeDefault
